### PR TITLE
Add app.manifest for SSAI compatibility

### PR DESCRIPTION
**Pull request by sjukanti-splunk**
## Description

Add app.manifest for SSAI compatibility

## Motivation and Context

The app at the moment is not self service and required cloud ops cycles to install the app on a customer splunk cloud stack. With these changes, we would be one step closer to make this app SSAI (self service install)

## How Has This Been Tested?

Tested locally to ensure there would be no regression bugs

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by btorresgil** [comment]
@sjukanti-splunk can you share some documentation on how to support SSAI? I've scoured the docs at https://dev.splunk.com, but I don't see any details for app developers.  Thanks!

**Comment by btorresgil** [comment]
I found this: https://dev.splunk.com/enterprise/docs/developapps/testvalidate/appinspect/appinspectreferencetopics/splunkappinspectcheck/#Platform-targets-and-claimed-supported-Splunk-Enterprise-versions

> If json schema is 2.0.0 in app.manifest then warn it. Because schema version of 2.0.0 is not yet compatible with any versions of the Splunk Cloud.

Not sure if this is outdated information?

**Comment by sjukanti-splunk** [comment]
Hi @btorresgil, sorry for the delayed response. Here is the documentation related to the file: app.manifest - https://dev.splunk.com/enterprise/docs/releaseapps/packagingtoolkit/pkgtoolkitref/pkgtoolkitapp/#JSON-schema-200

In the efforts to make Palo Alto App and TA SSAI compatible, we have internally identified that adding an app.manifest with "targetWorkloads" and "supportedDeployments" fields with corresponding values will help make Splunk understand where the app and TA need to be installed, thus making it SSAI compatible.

I created this PR for the PA app and [PR](https://github.com/PaloAltoNetworks/Splunk_TA_paloalto/pull/58) for the TA, I just noticed that the TA repo against which I created the TA PR is archived. Let me create a new PR on the latest repo - https://github.com/PaloAltoNetworks/Splunk-Apps that I got from our PM Nick Filippi.

**Comment by btorresgil** [comment]
Thanks @sjukanti-splunk, we combined the App and Add-on into this single repository, so you can PR against both here.

Should we be using the `slim generate-manifest` command to generate the manifest file? Or should we use your PR instead?

Is manifest version 2.0.0 working on Splunk Cloud? The link I posted above says it doesn't, but I'm not sure if that's outdated info.

Thanks!!
 -Brian

**Comment by sjukanti-splunk** [comment]
Hi Brian, 
`slim generate-manifest` generates the manifest file, but unfortunately it doesn't do a very good job on identifying the values for `targetWorkloads` and `supportedDeployments` which is what we want to address as part of this PR to make these SSAI compatible. Hence I hand created the app.manifest file here.

Regarding 2.0.0 not being compatible with Splunk Cloud, as suspected is outdated, sorry for the confusion. Hope this clarifies.

**Comment by sjukanti-splunk** [comment]
@btorresgil I have the version for both App and TA as `"version": "6.3.1"`. Please feel free to bump up the version accordingly for the next release of these packages.

**Pull request merged**
